apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-02-29T14:03:46Z"
  generation: 2
  labels:
    app: pyco-cicd
  name: pyco-cicd
  namespace: default
  resourceVersion: "98066"
  uid: 5267fa5d-505d-4343-841e-ca56b95d3d28
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pyco-cicd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pyco-cicd
    spec:
      containers:
      - image: ghcr.io/ci-cd-2024-dhbw-hdh/pyco-cicd:latest
        imagePullPolicy: Always
        name: pyco-cicd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-29T14:32:25Z"
    lastUpdateTime: "2024-02-29T14:32:25Z"
    message: ReplicaSet "pyco-cicd-79d84c676" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-03-06T07:58:48Z"
    lastUpdateTime: "2024-03-06T07:58:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1