apiVersion: v1
kind: Service
metadata:
  labels:
    app: pyco-svc
  name: pyco-svc
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-80
    nodePort: 30919
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: pyco-cicd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}