name: Digital Ocean Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Create namespace
        run: kubectl create namespace pyco-cicd --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml
  verify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - run: kubectl rollout status deployment/pyco-cicd