name: Digital Ocean Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Create namespace
        run: kubectl create namespace pyco-cicd --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy
        run: |
          kubectl create secret docker-registry regcred --docker-server=ghcr.io --docker-username=${{ github.actor }} --docker-password=${{ secrets.GITHUB_TOKEN }}
          kubectl apply -n pyco-cicd -f deployment/deployment.yaml
          kubectl apply -n pyco-cicd -f deployment/service.yaml